version: '3.9'

services:
  api_express:
    container_name: api_express
    image: node:17-alpine
    build: ./backend/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:latest
    env_file: ./backend/.env
    ports:
      - 5432:5432

  client:
    container_name: client
    image: docker-react-i
    build: ./frontend/Dockerfile
    ports:
      - 3001:3001
    depends_on:
      - db
      - api_express
